syntax = "proto3";

package gen;

option go_package = "github.com/kacperborowieckb/gen-sql/shared/gen";

service DataService {
  rpc StartDataGeneration(StartDataGenerationRequest) returns (StartDataGenerationResponse);
  rpc GetProjectData(GetProjectDataRequest) returns (GetProjectDataResponse);
  rpc GetProjects(GetProjectsRequest) returns (GetProjectsResponse);
  rpc DeleteProject(DeleteProjectRequest) returns (DeleteProjectResponse);
}

message StartDataGenerationRequest {
  string project_id = 1;
  string ddl_schema = 2;
  int32 rows_to_generate = 3;
  string instructions = 4;
  float temperature = 5;
}

message StartDataGenerationResponse {
  string generation_job_id = 1;
  string message = 2;
  bool success = 3;
}

message GetProjectDataRequest {
  string project_id = 1;
}

message GetProjectDataResponse {
  string json_data = 1;
}

message GetProjectsRequest {}

message GetProjectsResponse {
  repeated string project_ids = 1;
}

message DeleteProjectRequest {
  string project_id = 1;
}

message DeleteProjectResponse {
  bool success = 1;
  string message = 2;
}
